### ISSUE TITLE
ArduCopter version

### ISSUE THREAD

**Issue by shubham9436** [erlerobot/ardupilot-binaries#1]
Will there be any version upgradation for ArduCopter?
i think right now, it is currently running on 3.4.
I want to change the yaw angle of erlecopter in ROS SITL Gazebo, but it is behaving very weirdly.

**Comment by LanderU** [comment]
Hello @shubham9436,

this repo is deprecated. We're not going to update it. If you need the new ArduPilot firmware version, you need to compile the code, or download it from our deb packages server (only available for our customers).
